version: "3"

services:
  git_builder:
    build: ./git-builder
    image: git-builder:latest
    environment:
      GIT_URL: /usr/src/repo
    volumes:
      - src:/usr/src/app
      - /home/sgillespie/dev/react-boilerplate:/usr/src/repo

  node_builder:
    build: ./node-builder
    image: node-builder
    volumes:
      - src:/usr/src/app

  orchestrator:
    build: ./orchestrator
    image: orchestrator
    environment:
      BUILD_TAG: react-boilerplate
      DOCKERFILE: /dockerfiles/nginx.dockerfile
      GIT_URL: /usr/src/repo
    volumes:
      - src:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/sgillespie/dev/react-boilerplate:/usr/src/repo

volumes:
  src:
  git_repo:
